openapi: 3.0.1
info:
  title: Shop
  version: 1.0.0
components:
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "api_key"
      in: "header"
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        password:
          type: string
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        price:
          type: integer
          format: int64
        image_link:
          type: string
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        product_id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        count:
          type: integer
          format: int64
paths:
  /user/login:
    post:
      tags: ["user"]
      operationId: loginUser
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          headers:
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
        400:
          description: Invalid username/password supplied
          content: {}
  /user/logout:
    post:
      tags: ["user"]
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        200:
          description: successful logout
          content: {}
  /items:
    post:
      tags: ["items"]
      summary: "Add a new item to the store"
      operationId: "CreateItem"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "405":
          description: "Invalid input"
      security:
      - api_key: []
    get:
      tags: ["items"]
      summary: Lists Items with filters
      operationId: ListItems
      parameters:
      - name: price_min
        in: query
        description: Lower price limit
        required: false
        schema:
          type: integer
          format: int64
      - name: price_max
        in: query
        description: Upper price limit
        required: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        400:
         description: Invalid price range
         content: {}
  /items/upload_image:
    post:
      tags: ["items"]
      summary: "uploads an image"
      operationId: "uploadFile"
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
          application/json:
            schema:
              type: "array"
              items:
                $ref: '#/components/schemas/Item'
      responses:
        400:
          description: Invalid image
          content: {}
      security:
      - api_key: []
  /items/{itemId}:
    get:
      tags: ["items"]
      summary: Find item by ID
      operationId: GetItem
      parameters:
      - name: itemId
        in: path
        description: ID of item to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        400:
          description: Invalid ID supplied
          content: {}
    put:
      tags: ["items"]
      summary: Updates a item in the store with form data
      operationId: UpdateItem
      parameters:
      - name: itemId
        in: path
        description: ID of item that needs to be updated
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  description: Updated name of the item
                status:
                  type: string
                  description: Updated status of the item
      responses:
        405:
          description: Invalid input
          content: {}
      security:
      - api_key: []
    delete:
      tags: ["items"]
      summary: Deletes a item
      operationId: DeleteItem
      parameters:
      - name: itemId
        in: path
        description: Item id to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Item not found
          content: {}
      security:
      - api_key: []
  /orders:
    post:
      tags: ["orders"]
      summary: "Add a new order to the store"
      operationId: "CreateOrder"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "405":
          description: "Invalid input"
    get:
      tags: ["orders"]
      summary: "Lists Orders with filters"
      operationId: "ListOrders"
      parameters:
      - name: "date_from"
        in: "query"
        description: "date beginning"
        required: false
        schema:
          type: "string"
      - name: "date_to"
        in: "query"
        description: "end date"
        required: false
        schema:
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Order'
        400:
         description: "Invalid date range"
         content: {}
      security:
      - api_key: []  
  /orders/{orderId}:
    get:
      tags: ["orders"]
      summary: "Find order by ID"
      operationId: "GetOrder"
      parameters:
      - name: "orderId"
        in: "path"
        description: "ID of order to return"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        400:
          description: "Invalid ID supplied"
          content: {}
      security:
      - api_key: []  
    put:
      tags: ["orders"]
      summary: "Updates a order in the store with form data"
      operationId: "UpdateOrder"
      parameters:
      - name: "orderId"
        in: "path"
        description: "ID of order that needs to be updated"
        required: true
        schema:
          type: "integer"
          format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                count:
                  type: "integer"
                  format: "int64"
                  description: "Updated count of the order"
                user_id:
                  type: "integer"
                  format: "int64"
                  description: "Updated user id of the order"
                product_id:
                  type: "integer"
                  format: "int64"
                  description: "Updated product id of the order"
      responses:
        405:
          description: "Invalid input"
          content: {}
      security:
      - api_key: [] 
    delete:
      tags: ["orders"]
      summary: "Deletes a order"
      operationId: "DeleteOrder"
      parameters:
      - name: "orderId"
        in: "path"
        description: "Order id to delete"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
          content: {}
        404:
          description: "Order not found"
          content: {}
      security:
      - api_key: []
  /orders/{userId}/user_orders:
    get:
      tags: ["orders"]
      summary: "Get all orders for user"
      operationId: "ListUserOrders"
      parameters:
      - name: "userId"
        in: "path"
        description: "User id"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Order'
        400:
         description: "Invalid user id range"
         content: {}
      security:
      - api_key: []  
